name: Partial Sync Notion Star

on:
  schedule:
    - cron: '0 0 */7 * *'
  push:
    paths:
      - 'github_sync.py'

env:
  GITHUB_TOKEN :  ${{ secrets.GITHUB_TOKEN }}
  NOTION_TOKEN : ${{ secrets.NOTION_TOKEN }}
  NOTION_DATABASE : ${{ secrets.NOTION_DATABASE }}

jobs:
  partial-sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    environment: notion-sync
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          python github_sync.py
